#!/usr/bin/env python3
"""
AI Content Platform - One-Click Setup
======================================

This script sets up everything you need to run the platform:
1. Creates .env file from your inputs
2. Sets up the database
3. Seeds default data
4. Creates an admin user
5. Verifies all services are configured

Usage:
    python setup.py

Requirements:
    - Python 3.9+
    - PostgreSQL database
    - Redis (optional, for Celery)
"""

import os
import sys
import secrets
import subprocess
from pathlib import Path

# Colors for terminal output
class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    END = '\033[0m'
    BOLD = '\033[1m'

def print_header(text):
    print(f"\n{Colors.HEADER}{Colors.BOLD}{'='*60}{Colors.END}")
    print(f"{Colors.HEADER}{Colors.BOLD}{text.center(60)}{Colors.END}")
    print(f"{Colors.HEADER}{Colors.BOLD}{'='*60}{Colors.END}\n")

def print_step(step, text):
    print(f"{Colors.CYAN}[{step}]{Colors.END} {text}")

def print_success(text):
    print(f"{Colors.GREEN}✅ {text}{Colors.END}")

def print_warning(text):
    print(f"{Colors.WARNING}⚠️  {text}{Colors.END}")

def print_error(text):
    print(f"{Colors.FAIL}❌ {text}{Colors.END}")

def print_info(text):
    print(f"{Colors.BLUE}ℹ️  {text}{Colors.END}")

def get_input(prompt, default=None, required=True, secret=False):
    """Get user input with optional default value."""
    if default:
        display_prompt = f"{prompt} [{default}]: "
    else:
        display_prompt = f"{prompt}: "
    
    if secret:
        import getpass
        value = getpass.getpass(display_prompt)
    else:
        value = input(display_prompt).strip()
    
    if not value and default:
        return default
    
    if not value and required:
        print_error(f"{prompt} is required!")
        return get_input(prompt, default, required, secret)
    
    return value

def generate_secret_key():
    """Generate a secure secret key."""
    return secrets.token_urlsafe(32)

def check_python_version():
    """Check if Python version is 3.9+."""
    if sys.version_info < (3, 9):
        print_error(f"Python 3.9+ required. You have {sys.version}")
        sys.exit(1)
    print_success(f"Python {sys.version_info.major}.{sys.version_info.minor} detected")

def install_dependencies():
    """Install Python dependencies."""
    print_step("2", "Installing Python dependencies...")
    try:
        subprocess.run([sys.executable, "-m", "pip", "install", "-r", "requirements.txt", "-q"], check=True)
        print_success("Dependencies installed")
    except subprocess.CalledProcessError:
        print_error("Failed to install dependencies")
        sys.exit(1)

def create_env_file(config):
    """Create .env file from configuration."""
    env_content = f"""# AI Content Platform Configuration
# Generated by setup.py

# ===================
# Core Settings
# ===================
APP_NAME=AI Content Platform
DEBUG={config.get('debug', 'false')}
SECRET_KEY={config['secret_key']}
FRONTEND_URL={config['frontend_url']}

# ===================
# Database
# ===================
DATABASE_URL={config['database_url']}

# ===================
# Redis (for Celery)
# ===================
REDIS_URL={config.get('redis_url', 'redis://localhost:6379/0')}

# ===================
# AI Services
# ===================
OPENAI_API_KEY={config.get('openai_api_key', '')}
REPLICATE_API_TOKEN={config.get('replicate_api_token', '')}
ANTHROPIC_API_KEY={config.get('anthropic_api_key', '')}

# ===================
# Stripe Billing
# ===================
STRIPE_SECRET_KEY={config.get('stripe_secret_key', '')}
STRIPE_PUBLISHABLE_KEY={config.get('stripe_publishable_key', '')}
STRIPE_WEBHOOK_SECRET={config.get('stripe_webhook_secret', '')}

# Stripe Price IDs
STRIPE_PRICE_CREATOR={config.get('stripe_price_creator', '')}
STRIPE_PRICE_PRO={config.get('stripe_price_pro', '')}
STRIPE_PRICE_AGENCY={config.get('stripe_price_agency', '')}

# ===================
# Email (SMTP)
# ===================
SMTP_HOST={config.get('smtp_host', 'smtp.gmail.com')}
SMTP_PORT={config.get('smtp_port', '587')}
SMTP_USER={config.get('smtp_user', '')}
SMTP_PASSWORD={config.get('smtp_password', '')}
EMAIL_FROM={config.get('email_from', '')}

# ===================
# OAuth (Optional)
# ===================
GOOGLE_CLIENT_ID={config.get('google_client_id', '')}
GOOGLE_CLIENT_SECRET={config.get('google_client_secret', '')}
GITHUB_CLIENT_ID={config.get('github_client_id', '')}
GITHUB_CLIENT_SECRET={config.get('github_client_secret', '')}

# ===================
# Social Media APIs (Optional)
# ===================
TWITTER_API_KEY={config.get('twitter_api_key', '')}
TWITTER_API_SECRET={config.get('twitter_api_secret', '')}
INSTAGRAM_APP_ID={config.get('instagram_app_id', '')}
INSTAGRAM_APP_SECRET={config.get('instagram_app_secret', '')}
LINKEDIN_CLIENT_ID={config.get('linkedin_client_id', '')}
LINKEDIN_CLIENT_SECRET={config.get('linkedin_client_secret', '')}
FACEBOOK_APP_ID={config.get('facebook_app_id', '')}
FACEBOOK_APP_SECRET={config.get('facebook_app_secret', '')}

# ===================
# Error Tracking (Optional)
# ===================
SENTRY_DSN={config.get('sentry_dsn', '')}

# ===================
# File Storage (Optional)
# ===================
AWS_ACCESS_KEY_ID={config.get('aws_access_key_id', '')}
AWS_SECRET_ACCESS_KEY={config.get('aws_secret_access_key', '')}
AWS_S3_BUCKET={config.get('aws_s3_bucket', '')}
AWS_REGION={config.get('aws_region', 'us-east-1')}
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print_success(".env file created")

def setup_database():
    """Set up the database tables."""
    print_step("4", "Setting up database...")
    
    try:
        from app.database_setup import create_all_tables, seed_default_data
        create_all_tables()
        seed_default_data()
        print_success("Database setup complete")
    except Exception as e:
        print_error(f"Database setup failed: {e}")
        print_info("Make sure your DATABASE_URL is correct and the database exists")
        return False
    
    return True

def create_admin_user(email, password):
    """Create an admin user."""
    print_step("5", "Creating admin user...")
    
    try:
        from app.core.database import SessionLocal
        from app.admin.models import AdminUser
        from app.auth.security import get_password_hash
        
        db = SessionLocal()
        
        # Check if admin exists
        existing = db.query(AdminUser).filter(AdminUser.email == email).first()
        if existing:
            print_warning(f"Admin user {email} already exists")
            db.close()
            return True
        
        # Create admin
        admin = AdminUser(
            email=email,
            hashed_password=get_password_hash(password),
            full_name="Admin",
            role="super_admin",
            is_active=True
        )
        db.add(admin)
        db.commit()
        db.close()
        
        print_success(f"Admin user created: {email}")
        return True
    except Exception as e:
        print_error(f"Failed to create admin: {e}")
        return False

def setup_frontend():
    """Set up the frontend."""
    print_step("6", "Setting up frontend...")
    
    frontend_path = Path("frontend")
    if not frontend_path.exists():
        print_warning("Frontend directory not found")
        return False
    
    # Check if npm is available
    try:
        subprocess.run(["npm", "--version"], capture_output=True, check=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        print_warning("npm not found - skipping frontend setup")
        print_info("Install Node.js and run 'npm install' in the frontend directory")
        return False
    
    # Install frontend dependencies
    try:
        os.chdir("frontend")
        subprocess.run(["npm", "install"], capture_output=True, check=True)
        os.chdir("..")
        print_success("Frontend dependencies installed")
        return True
    except subprocess.CalledProcessError:
        os.chdir("..")
        print_warning("Frontend setup failed - you can do this manually later")
        return False

def verify_setup():
    """Verify the setup is complete."""
    print_step("7", "Verifying setup...")
    
    checks = []
    
    # Check .env exists
    if Path(".env").exists():
        checks.append(("Environment file", True))
    else:
        checks.append(("Environment file", False))
    
    # Check database connection
    try:
        from app.core.database import engine
        from sqlalchemy import text
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        checks.append(("Database connection", True))
    except:
        checks.append(("Database connection", False))
    
    # Check required API keys
    from app.core.config import get_settings
    settings = get_settings()
    
    checks.append(("OpenAI API Key", bool(settings.openai_api_key)))
    checks.append(("Replicate API Token", bool(settings.replicate_api_token)))
    checks.append(("Stripe Keys", bool(settings.stripe_secret_key)))
    
    print("\n" + "="*50)
    print("Setup Verification Results:")
    print("="*50)
    
    all_passed = True
    for check_name, passed in checks:
        if passed:
            print(f"  {Colors.GREEN}✓{Colors.END} {check_name}")
        else:
            print(f"  {Colors.FAIL}✗{Colors.END} {check_name}")
            all_passed = False
    
    print("="*50)
    
    return all_passed

def print_next_steps():
    """Print next steps after setup."""
    print_header("Setup Complete! 🎉")
    
    print(f"""
{Colors.GREEN}Your AI Content Platform is ready!{Colors.END}

{Colors.BOLD}To start the backend:{Colors.END}
    cd ai-content-platform
    uvicorn app.main:app --reload --port 8000

{Colors.BOLD}To start the frontend:{Colors.END}
    cd ai-content-platform/frontend
    npm run dev

{Colors.BOLD}To start Celery workers (for background tasks):{Colors.END}
    cd ai-content-platform
    celery -A app.worker worker --loglevel=info
    celery -A app.worker beat --loglevel=info

{Colors.BOLD}Access points:{Colors.END}
    • Frontend: http://localhost:5173
    • Backend API: http://localhost:8000
    • API Docs: http://localhost:8000/docs
    • Admin Panel: http://localhost:8000/admin

{Colors.BOLD}Optional - Configure these for full functionality:{Colors.END}
    • Social media API keys (for posting)
    • Stripe webhook endpoint
    • Email SMTP settings
    • Sentry for error tracking

{Colors.CYAN}Need help? Check the documentation:{Colors.END}
    • QUICK-START.md
    • DEPLOYMENT.md
    • PRODUCTION_READINESS.md
""")

def main():
    """Main setup function."""
    print_header("AI Content Platform Setup")
    
    print("This wizard will help you set up the AI Content Platform.")
    print("You'll need the following ready:")
    print("  • PostgreSQL database URL")
    print("  • OpenAI API key (for content generation)")
    print("  • Replicate API token (for image generation)")
    print("  • Stripe keys (for billing - can skip for testing)")
    print()
    
    proceed = get_input("Ready to proceed? (yes/no)", default="yes")
    if proceed.lower() not in ['yes', 'y']:
        print("Setup cancelled.")
        sys.exit(0)
    
    config = {}
    
    # Step 1: Check Python version
    print_step("1", "Checking Python version...")
    check_python_version()
    
    # Step 2: Install dependencies
    install_deps = get_input("Install Python dependencies?", default="yes")
    if install_deps.lower() in ['yes', 'y']:
        install_dependencies()
    
    # Step 3: Collect configuration
    print_step("3", "Collecting configuration...")
    print()
    
    # Essential settings
    print(f"{Colors.BOLD}Essential Settings:{Colors.END}")
    config['database_url'] = get_input(
        "PostgreSQL Database URL",
        default="postgresql://user:password@localhost:5432/ai_content"
    )
    config['secret_key'] = generate_secret_key()
    config['frontend_url'] = get_input("Frontend URL", default="http://localhost:5173")
    config['debug'] = get_input("Debug mode?", default="false")
    
    print()
    print(f"{Colors.BOLD}AI Services:{Colors.END}")
    config['openai_api_key'] = get_input("OpenAI API Key", required=False)
    config['replicate_api_token'] = get_input("Replicate API Token", required=False)
    
    print()
    print(f"{Colors.BOLD}Stripe Billing (press Enter to skip):{Colors.END}")
    config['stripe_secret_key'] = get_input("Stripe Secret Key", required=False)
    config['stripe_publishable_key'] = get_input("Stripe Publishable Key", required=False)
    
    print()
    print(f"{Colors.BOLD}Redis (for background tasks):{Colors.END}")
    config['redis_url'] = get_input("Redis URL", default="redis://localhost:6379/0")
    
    # Create .env file
    create_env_file(config)
    
    # Now we can import app modules
    os.environ['DATABASE_URL'] = config['database_url']
    
    # Setup database
    if setup_database():
        # Create admin user
        print()
        print(f"{Colors.BOLD}Create Admin User:{Colors.END}")
        admin_email = get_input("Admin email", default="admin@example.com")
        admin_password = get_input("Admin password", default="admin123", secret=True)
        create_admin_user(admin_email, admin_password)
    
    # Setup frontend
    setup_frontend()
    
    # Verify
    verify_setup()
    
    # Print next steps
    print_next_steps()

if __name__ == "__main__":
    main()
